name = too_many_tnt
title = Too Much TNT!
description = Adds a lot of TNT for Minetest Game to make gameplay more fun!
author = SkyBuilder1717
depends = default, tnt, basic_materials, bucket, uraniumstuff, mobs, wool, dye
optional_depends = mesecons, lucky_block, ethereal, xdecor, stairs, laptop, doors, homedecor_common, decor_api, gloopblocks, mobs_monster, fireworks, flowers